"""
Temp Scanner: Scans Windows user and system temporary folders.
"""

import os
from typing import List, Optional
from cleanguard.core.scanner.base import BaseScanner, CancellationToken, ProgressCallback
from cleanguard.core.contracts import ScanItem, CleanCategory
from cleanguard.windows.known_folders import get_known_folders


class TempScanner(BaseScanner):
    """Scans %TEMP% (User Temp) and %SystemRoot%\\Temp (System Temp)."""

    @property
    def scanner_id(self) -> str:
        return "temp_scanner"

    @property
    def display_name(self) -> str:
        return "Temporary Files"

    @property
    def category(self) -> CleanCategory:
        return CleanCategory.TEMP_FILES

    def get_allowed_roots(self) -> List[str]:
        folders = get_known_folders()
        roots = []
        if folders.user_temp and os.path.exists(folders.user_temp):
            roots.append(folders.user_temp)
        if folders.system_temp and os.path.exists(folders.system_temp):
            roots.append(folders.system_temp)
        return roots

    def scan(
        self,
        cancel_token: Optional[CancellationToken] = None,
        progress_callback: Optional[ProgressCallback] = None,
    ) -> List[ScanItem]:
        items: List[ScanItem] = []
        for root in self.get_allowed_roots():
            if cancel_token and cancel_token.is_cancelled():
                break
            found = self.safe_scan_directory(
                root_dir=root,
                cancel_token=cancel_token,
                progress_callback=progress_callback,
                rule_id="RULE-TEMP-CLEAN",
                default_reason="Temporary file generated by system or application.",
            )
            for it in found:
                if "PyInstaller" in it.reason:
                    it.rule_id = "RULE-PYINSTALLER-ORPHAN"
            items.extend(found)
        return items
